codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 60%  # Gradually increasing from 57% baseline
        threshold: 1%
        base: auto
    patch:
      default:
        target: 60%  # New code should have at least 60% coverage
        threshold: 1%

flags:
  unittests:
    paths:
      - pywiim/

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: false

