codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 55%  # Current baseline: 56.68%, gradually increasing
        threshold: 1%
        base: auto
    patch:
      default:
        target: 55%  # Current patch: 58.85%, gradually increasing
        threshold: 1%

ignore:
  - "scripts/**/*"  # Manual test scripts don't need unit test coverage
  - "tests/**/*"    # Test files themselves

flags:
  unittests:
    paths:
      - pywiim/

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: false

